const CACHE_TAGS = {
  BRANCH: {
    GET_OWNER_BRANCHES: "BRANCH_GET_OWNER_BRANCHES",
    GET_BRANCH_BY_ID: "BRANCH_GET_BRANCH_BY_ID",
  },
  FIELD: {
    GET_FIELDS_OF_BRANCH: "FIELD_GET_FIELDS_OF_BRANCH",
    GET_BY_ID: "FIELD_GET_BY_ID",
  },
  TOURNAMENT: {
    GET_BRANCH_TOURNAMENTS: "TOURNAMENT_GET_BRANCH_TOURNAMENTS",
    GET_BY_ID: "TOURNAMENT_GET_BY_ID",
  },
  RATE: {
    OBJECT: "RATE_OBJECT",
  },
  FIELD_BOOKED_QUEUE: {
    GET_FIELD_BOOKED_QUEUE: "FIELD_BOOKED_QUEUE_GET_FIELD_BOOKED_QUEUE",
  },
  PRIZE: {
    BRANCH: "PRIZE_BRANCH",
  },
  MATCH: {
    GET_BY_ID: "MATCH_GET_BY_ID",
  },
  INVOICE: {
    GET_INVOICE: "INVOICE_GET_INVOICE",
  },
}

export default CACHE_TAGS
