import type { Metadata } from "next"
import { Lexend } from "next/font/google"
import React from "react"
import { Toaster } from "react-hot-toast"
import "./globals.css"

const inter = Lexend({ subsets: ["latin", "vietnamese"] })

export const metadata: Metadata = {
  title: "Owner Dashboard | Footex",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background`}>
        <div>{children}</div>
        <Toaster
          toastOptions={{
            duration: 3000,
            position: "bottom-center",
          }}
        />
      </body>
    </html>
  )
}
